spring:
  data:
    mongodb:
      # uri: mongodb://localhost/?directConnection=true
      uri: mongodb://root:secret@localhost:27017
      database: test

  ai:
    openai:
      api-key: ${openaiApiKey}


server:
  error:
    include-message: always
    include-binding-errors: always
